#!/usr/bin/env bash
function stop() {
    echo "$@"
    exit 1
}

function RUN() {
    if __DRY_RUN__; then
        echo "DRY-RUN: $@"
    else
        echo "RUNNING: $@"
        "$@" || stop "Failed"
    fi
}

function copyConfig() {
    cat << EOF > '.wxrc'
{
    "config": [
        "docker-compose.yml",
        "start.sh",
        "hosts"
    ]
}
EOF
}

function copyRcLocal() {
    cat << EOF | sudo tee "/etc/rc.local" > /dev/null
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
__WD__/start.sh || exit 1
exit 0
EOF
}

function copyHosts() {
    cat "/etc/hosts.d/original.hosts" "/etc/hosts.d/wx.hosts" | sudo tee "/etc/hosts" > /dev/null
}

dir="__WD__"
if [ ! -d "$dir" ]; then
    RUN mkdir "$dir"
fi
RUN cd "$dir"
RUN copyConfig
RUN wx-client-config --project root

# HOSTS
if [ ! -f "/etc/hosts.d/original.hosts" ]; then
    RUN sudo mkdir -p "/etc/hosts.d"
    RUN sudo cp "/etc/hosts" "/etc/hosts.d/original.hosts"
fi
RUN sudo cp "hosts" "/etc/hosts.d/wx.hosts"
RUN copyHosts

# START
RUN copyRcLocal
