#!/usr/bin/env bash
function stop() {
    echo "$@"
    exit 1
}

function RUN() {
    if __DRY_RUN__; then
        echo "DRY-RUN: $@"
    else
        echo "RUNNING: $@"
        "$@" || stop "Failed"
    fi
}

RUN cd "__WD__/__NAME__"
RUN git pull
if [ -f ".wxrc" ]; then
    RUN wx-client-config
fi
RUN wx install
